name: Build and test cinnamon
run-name: 'Build and Test: ${{ github.event.head_commit.message }}'
on: 
  workflow_dispatch:
  push:
jobs:
  main:
    name: Build and test
    runs-on: ubuntu-22.04
    env:
      CC: clang
      CXX: clang++
      LDFLAGS: -fuse-ld=mold
      CMAKE_GENERATOR: Ninja

    steps: 
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: sudo apt-get install clang ninja-build mold libvulkan-dev

      - name: Cache llvm build
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm
          key: llvm-build-${{ runner.os }}
          restore-keys: |
            llvm-build-${{ runner.os }}
      
      - name: Build 
        run: .github/workflows/build-ci.sh
      
      - name: Test
        working-directory: cinnamon/build
        run: ninja check-cinm-mlir